manifest:
  version: 0.13

  defaults:
    remote: zephyrproject

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    # Zephyr RTOS sources. west will clone this into thirdparty/zephyrproject/zephyr
    - name: zephyr
      remote: zephyrproject
      revision: v4.2.0
      path: thirdparty/zephyrproject/zephyr
      import:
        path-prefix: thirdparty/zephyrproject

  self:
    path: .west
